#!/bin/bash


read -p "Souhaitez-vous enregistrer des informations sur ce commit (y/[n]) ? " yn < /dev/tty
yn=${yn:n}


case $yn in
 [Yy]* )

    mkdir -p suivi


    echo "commit vérifié le $(date)" > suivi/commitInfo.txt

 
    git add suivi/commitInfo.txt
    ;;
 [Nn]* )
   
    ;;
 *)
    
    ;;
esac
